### ISSUE TITLE
能否增加病例确诊时间数据

### ISSUE THREAD

**Issue by RangeKing** [hack-fang/ncov-map#1]
非常感谢免费公开详细地点的数据，对我们团队的研究非常有帮助。
请问是否方便增加每个病例确诊时间的数据，非常感谢！

**Comment by hack-fang** [comment]
> 
> 
> 非常感谢免费公开详细地点的数据，对我们团队的研究非常有帮助。
> 请问是否方便增加每个病例确诊时间的数据，非常感谢！

感谢支持，但目前病例的公布信息基本是集中发布的，无法收集到每个病例确诊时间。

**Comment by hack-fang** [comment]
> 
> 
> 非常感谢免费公开详细地点的数据，对我们团队的研究非常有帮助。
> 请问是否方便增加每个病例确诊时间的数据，非常感谢！

目前增加了每个病例的消息来源的链接，不知道是否对你有帮助

**Comment by jackberry** [comment]
> 非常感谢免费公开详细地点的数据，对我们团队的研究非常有帮助。
> 请问是否方便增加每个病例确诊时间的数据，非常感谢！

Wuhan 2020那个项目收集的信息有确诊时间

**Comment by keeponlight** [comment]
> > 非常感谢免费公开详细地点的数据，对我们团队的研究非常有帮助。
> > 请问是否方便增加每个病例确诊时间的数据，非常感谢！
> 
> Wuhan 2020那个项目收集的信息有确诊时间

请问地址是哪个

**Comment by hack-fang** [comment]
现已更新 **疫情小区发布时间字段**，值为**unix秒形式**，详情: https://github.com/hack-fang/ncov-map
