### ISSUE TITLE
非常感谢提供这么详细的数据！不过数据已经有好多天没有更新了，请问是否还会更新数据？

### ISSUE THREAD

**Issue by HipoFirst** [hack-fang/ncov-map#2]
非常感谢提供这么详细的数据！对我们的帮助很大，
不过数据已经有好多天没有更新了，请问是否还会更新数据？

**Comment by hack-fang** [comment]
> 
> 
> 非常感谢提供这么详细的数据！对我们的帮助很大，
> 不过数据已经有好多天没有更新了，请问是否还会更新数据？

感谢支持，数据每天是通过爬虫等方式更新(每天两次)，不过也存在某些地区没有更新的情况(缺少数据来源)，计划目前部分的地区计划通过手动方式添加。

**Comment by hack-fang** [comment]
> 
> 
> 非常感谢提供的数据接口，目前临沂的数据很久没有更新了，可否更新一下数据？

看了下  [临沂市卫生健康委员会](http://wsjsw.linyi.gov.cn/gsgg.htm)   发布的数据，最新一条为2.14日发布的，数据库已经是最新的数据了。。
