### ISSUE TITLE
增加一定范围内疫情数的接口的需求

### ISSUE THREAD

**Issue by keeponlight** [hack-fang/ncov-map#3]
非常感谢提供这么详细的数据和接口，而且每日更新，对我们的帮助很大！
请问是否方便增加一定范围内疫情数的接口
若有需要，我们也很乐意提供帮助

**Comment by hack-fang** [comment]
感谢支持，我不是很清楚你说的范围是指的是什么？是时间范围还是地区范围？

**Comment by keeponlight** [comment]
> 感谢支持，我不是很清楚你说的范围是指的是什么？是时间范围还是地区范围？

地区范围比如3km内感染数，然后目前这个是访问有限制，每天1万然后每秒5次吗，我们是协和团队做的诊疗系统目的是节省医生暴露的时间和救更多的人，可能到时候访问量比较大，谢谢

**Comment by hack-fang** [comment]
> 
> 
> > 感谢支持，我不是很清楚你说的范围是指的是什么？是时间范围还是地区范围？
> 
> 地区范围比如3km内感染数，然后目前这个是访问有限制，每天1万然后每秒5次吗，我们是协和团队做的诊疗系统目的是节省医生暴露的时间和救更多的人，可能到时候访问量比较大，谢谢

致敬您的工作，目前访问量没有限制，访问量比较大的问题暂时还没有遇到，还有几台空的服务器，如果真遇到访问量的问题，可以启用。不过我没能理解您要表达的是什么，你可以加我的qq:747425216  沟通。

**Comment by keeponlight** [comment]
> > > 感谢支持，我不是很清楚你说的范围是指的是什么？是时间范围还是地区范围？
> > 
> > 
> > 地区范围比如3km内感染数，然后目前这个是访问有限制，每天1万然后每秒5次吗，我们是协和团队做的诊疗系统目的是节省医生暴露的时间和救更多的人，可能到时候访问量比较大，谢谢
> 
> 致敬您的工作，目前访问量没有限制，访问量比较大的问题暂时还没有遇到，还有几台空的服务器，如果真遇到访问量的问题，可以启用。不过我没能理解您要表达的是什么，你可以加我的qq:747425216 沟通。

感谢支持！我尽快跟开发小伙伴说让他联系您
